# Generated by Django 4.0.2 on 2022-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Имя пользователя')),
                ('second_name', models.TextField(verbose_name='Фамилия')),
                ('sex', models.BooleanField(verbose_name='Пол')),
                ('avatar', models.URLField(verbose_name='Аватар')),
                ('mail', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
        ),
    ]
